# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b149fd1b0034691f8c25e99ea553dcbf55f27236298ca4896e4bf36502cf4f311edbd0f25f53c805438973459b892a9d6796168d13de14de8204238124706486

test:
  secret_key_base: 03560ab668c8fb1dc674621bf74b796d7374de02cb8c35de5e63171f6276c081e70dc55d90ba5a73302e51576bab76eb2a083ea528dfc641a893f4889051c45f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
